# Pipeline settings
pipeline: specter
embedding: specter_v2
embedding_ndim: 768

# Data loading
papers_table: "test.test_papers_dataset"

# Output table location
table_save_path: "test.test_specter_db_2"
overwrite_table: True