from papery.core.llm.core import LLM
from typing import Optional
from papery.core.utils import load_prompt


class ContextModel:
    context: list[dict[str, str]]

    def __init__(
        self,
        llm: LLM,
        system_prompt: Optional[str] = None,
        context: Optional[list[dict[str, str]]] = None,
    ):
        """
        Initialises a ContextModel - an interface for LLMs with context tracking.

        Parameters
        ----------
        llm: LLM
            LLM interface to use. Get one with the `get_llm` factory method.
        system_prompt: str, optional
            System prompt to use.
        context: list[dict[str, str]]
            Initialise ContextModel with a pre-existing context history.
        """
        if (system_prompt is not None) and (context is not None):
            raise ValueError("Only one of `system_prompt` or `context` can be defined.")

        self.llm = llm
        if context:
            self.context = context
        else:
            self.context = []

        if system_prompt:
            self.add_context(system_prompt, "system")

    def prompt(self, prompt: str, log=True) -> str:
        """
        Prompts the LLM with a given prompt and returns the response.
        """
        self.add_context(prompt, "user")

        output = self.llm.call_sync(self.context)

        self.add_context(output, "assistant")

        return output

    def add_context(self, content: str, role: str):
        self.context.append({"content": content, "role": role})

    def reset_context(self):
        """
        Clears the conversational history of this ContextModel, besides the system prompt.
        """
        self.context = self.context[:1]

    def set_context(self, context: list[dict[str, str]]):
        """
        Sets the conversational history of this ContextModel to a pre-defined context.

        Parameters
        ----------
        context: list[dict[str, str]]
            A list of dicts with keys "content" and "role", representing the conversational history.
        """
        self.context = context

    def get_context(self) -> list[dict[str, str]]:
        """
        Gets the conversational history of this ContextModel.

        Returns
        -------
        list[dict[str, str]]
            A list of dicts with keys "content" and "role", representing the conversational history.
        """
        return self.context

    def set_llm(self, llm: LLM):
        """
        Sets the LLM interface used by this ContextModel.

        Parameters
        ----------
        llm: LLM
            LLM interface to use. Get one with the `get_llm` factory method.
        """
        self.llm = llm

    def generate(self) -> str:
        """
        Generates a response from the LLM based on the current context.

        Returns
        -------
        str
            The response generated by the LLM.
        """
        output = self.llm.call_sync(self.context)

        self.add_context(output, "assistant")
        return output
